---
- hosts: all
  tasks:
    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - tmux
        - neovim
        - reattach-to-user-namespace
        - zsh
        - zsh-completions
        - nvm
        - yarn
    - name: Install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    - name: Create .vimrc symlink
      file:
        src: '{{ playbook_dir }}/.vimrc'
        dest: '~/.vimrc'
        state: link
        force: true
    - name: Create vim.init symlink
      file:
        src: '{{ playbook_dir }}/.vimrc'
        dest: '~/.config/nvim/init.vim'
        state: link
        force: true
    - name: Create .tmux.conf symlink
      file:
        src: '{{ playbook_dir }}/.tmux.conf'
        dest: '~/.tmux.conf'
        state: link
        force: true
    - name: Create .zshrc symlink
      file:
        src: '{{ playbook_dir }}/.zshrc'
        dest: '~/.zshrc'
        state: link
        force: true
    - name: Create tmux scripts folder symlink
      file:
        src: '{{ playbook_dir }}/tmux'
        dest: '~/tmux'
        state: link
        force: true
    - name: Create plugged directory for nvim
      file:
        path: '~/.config/nvim/plugged'
        state: directory
        mode: 0755
    - name: Create bundle directory for nvim
      file:
        path: '~/.config/nvim/bundle'
        state: directory
        mode: 0755
    - name: Install Vim-plug
      # TODO: Change this to get_url
      shell: curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    - name: Install Vim-plugins
      shell: nvim -c ':PlugInstall' -c 'qa!'
